### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by FlorLouv** [Leiaz/python-awox-mesh-light#1]
Hello Leiaz,
Thank you for your work. I have an issue when I test your example : 

`root@debian:~/python-awox-mesh-light# python3 test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    mylight.connect ()
  File "/root/python-awox-mesh-light/awoxmeshlight/__init__.py", line 113, in connect
    self.btdevice.connect (self.mac)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 408, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 402, in _connect
    "Failed to connect to peripheral %s, addr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connect to peripheral A4:C1:38:79:0B:6C, addr type: public
`
Remove all association (remote,smartphone) is mandatory ?

Best regards

**Comment by Leiaz** [comment]
Bluepy can't connect to the device. It could mean your Bluetooth adapter is off, or the light is already connected. If you connected to the light with some tool like `bluetoothctl` or a Bluetooth GUI widget, it must be disconnected from there first. I haven't used the phone app or remote, so I didn't test, but you could try turning off the app or Bluetooth on the phone in case it stays connected to it.

I don't think you need to completely remove the associations (but didn't test). But only one thing can connect to the light at a time.

**Comment by BVISE** [comment]
I have the same Problem and no other device is connectet
