### ISSUE TITLE
setMesh(), light.off()... raises an Assertion Error

### ISSUE THREAD

**Issue by matthiaaas** [Leiaz/python-awox-mesh-light#9]
Hey Leiaz,

I get an error when I try to interact with my bulb. It works well to connect and disconnect but when I try to do setMesh(), light.off() or something else it raises an AssertionError and I've no idea why.
Ignoring this and continuing executing the script doesn't work and the error still exists.

Help would be awesome.

Regards

**Comment by Leiaz** [comment]
The complete error message would be helpful.

**Comment by matthiaaas** [comment]
`
Traceback (most recent call last):
	File "/home/pi/.../python-awox-mesh-light/main.py", line 17, in <module>
		mylight.setMesh("mesh_name", "mesh_pwd", "mesh_key")
	File "/home/pi/.../python-awox-mesh-light/awoxmeshlight/__init__.py", line 152, in setMesh
		assert (self.session_key)
	AssertionError
`

**Comment by Leiaz** [comment]
It means there is no `session_key` . Did you check if `connect` returned True ?

**Comment by matthiaaas** [comment]
It's `False`. What's the problem?

**Comment by Leiaz** [comment]
You can try to get more info with the debug messages [see here](https://github.com/Leiaz/python-awox-mesh-light#printing-some-debug-info).

**Comment by matthiaaas** [comment]
Yes, it raises and `Auth error`. Something is wrong with the password and/or the name of the bulb.

**Comment by Leiaz** [comment]
If you used the AWOX app, you have to get the password from the app in some way, or reset the light to default password, if you don't want to keep using the app.

Some [sniffed the packets sent by the app](https://github.com/Leiaz/python-awox-mesh-light/issues/3), if you have root access to your android device, with `adb root` for instance, you can try looking in the app config files (in /data/, although I didn't check).
